module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'perf',
        'refactor',
        'test',
        'docs',
        'chore',
        'ci',
        'style',
        'build',
        'revert',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'auth',
        'chat',
        'group',
        'topic',
        'doc',
        'entity',
        'editor',
        'search',
        'notif',
        'i18n',
        'backup',
        'settings',
        'security',
        'perf',
        'ci',
        'server',
        'mobile',
        'e2e',
      ],
    ],
    'subject-case': [0],
  },
};
